openapi: 3.0.0
tags:
  - name: Waffle
info:
  title: Waffle
  version: 1.0.0-pre1
  contact:
    name: Support
    url: 'https://waffle.rest/support'
    email: support@waffle.rest
  termsOfService: 'https://waffle.rest/v1/terms'
  license:
    name: License
    url: 'https://waffle.rest/v1/license'
  description: 'test'
servers:
  - url: 'https://waffle.rest/v1'
    description: Production Server
paths: {}
components:
  schemas: {}
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
security:
  - JWT: []
